services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER = jino
      - POSTGRES_PASSWORD = jino
      - POSTGRES_DB = sample_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: always
    environment:
      - MODEL_FILEPATH = models/iris_svc.onnx
      - LABEL_FILEPATH = models/label.json
      - DATABASE = sample_db
      - USER = jino
      - PASSWORD = jino
      - HOST = postgres
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    